version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    container_name: sisyphus-db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mateuszuran
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: